// Fake users scattered around a city centre (London default)
// Coords are fuzzed — approximate area only, as per real app behaviour

const BASE_LAT = 51.5074
const BASE_LNG = -0.1278

function offset(minM, maxM) {
  const r = (Math.random() * (maxM - minM) + minM) / 111320
  const angle = Math.random() * 2 * Math.PI
  const lat = BASE_LAT + r * Math.cos(angle)
  const lng = BASE_LNG + r * Math.sin(angle) / Math.cos(BASE_LAT * Math.PI / 180)
  // Add a small secondary fuzz so the map pin doesn't sit on the exact session coord
  const r2 = (Math.random() * 300 + 200) / 111320
  const a2 = Math.random() * 2 * Math.PI
  return {
    lat,
    lng,
    fuzzedLat: lat + r2 * Math.cos(a2),
    fuzzedLng: lng + r2 * Math.sin(a2) / Math.cos(lat * Math.PI / 180),
  }
}

const now = Date.now()

// Hide active "I'm Out" sessions after midnight UK time
const _ukHour = parseInt(
  new Date().toLocaleString('en-GB', { timeZone: 'Europe/London', hour: '2-digit', hour12: false }),
  10
)
const _isUKLateNight = _ukHour >= 0 && _ukHour < 7

export const DEMO_USER = {
  uid: 'demo-me',
  displayName: 'You',
  photoURL: null,
  phoneNumber: null,
  email: 'demo@hangger.app',
}

const _ACTIVE_SESSIONS = [
  {
    id: 'demo-session-1',
    userId: 'demo-user-1',
    displayName: 'Sophie', age: 27,
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk1.png',
    photos: ['https://ik.imagekit.io/nepgaxllc/uk1.png','https://ik.imagekit.io/nepgaxllc/uk3.png','https://ik.imagekit.io/nepgaxllc/uk5.png','https://ik.imagekit.io/nepgaxllc/uk7.png'],
    gender: 'female',
    bio: 'Love a good cocktail bar and terrible karaoke 🎤',
    activityType: 'cocktails',
    activities: ['cocktails', 'food', 'hangout'],
    lookingFor: 'Dating',
    area: 'Soho', city: 'London',
    status: 'active', venueId: 'venue-soho-bar', tier: 'vip',
    distanceKm: 0.3,
    expiresAtMs: now + 45 * 60 * 1000, startedAtMs: now - 15 * 60 * 1000,
    lat: 51.5135, lng: -0.1322,
  },
  {
    id: 'demo-session-2',
    userId: 'demo-user-2',
    displayName: 'Emma', age: 25,
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk3.png',
    photos: ['https://ik.imagekit.io/nepgaxllc/uk3.png','https://ik.imagekit.io/nepgaxllc/uk6.png','https://ik.imagekit.io/nepgaxllc/uk9.png'],
    gender: 'female',
    bio: 'Yoga mornings, wine evenings. Looking for good company ✨',
    activityType: 'wine',
    activities: ['wine', 'coffee', 'walk'],
    lookingFor: 'Dating',
    area: 'Covent Garden', city: 'London',
    status: 'active', venueId: 'venue-soho-bar', tier: 'pro',
    distanceKm: 0.6,
    expiresAtMs: now + 30 * 60 * 1000, startedAtMs: now - 20 * 60 * 1000,
    lat: 51.5131, lng: -0.1318,
  },
  {
    id: 'demo-session-3',
    userId: 'demo-user-3',
    displayName: 'Charlotte', age: 29,
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk4.png',
    gender: 'female',
    bio: 'Foodie and part-time art gallery wanderer 🍷',
    activityType: 'pizza',
    activities: ['pizza', 'wine', 'cinema'],
    lookingFor: 'Dating',
    area: 'Fitzrovia', city: 'London',
    status: 'active', venueId: 'venue-fitz-bistro',
    distanceKm: 1.1,
    expiresAtMs: now + 60 * 60 * 1000, startedAtMs: now - 10 * 60 * 1000,
    lat: 51.5198, lng: -0.1359,
  },
  {
    id: 'demo-session-4',
    userId: 'demo-user-4',
    displayName: 'Olivia', age: 24,
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk5.png',
    gender: 'female',
    bio: 'Up for spontaneous plans — life\'s too short to stay in 🌙',
    activityType: 'bowling',
    activities: ['bowling', 'fastfood', 'hangout'],
    lookingFor: 'Dating',
    area: 'Shoreditch', city: 'London',
    status: 'active', venueId: 'venue-hyde-pub',
    distanceKm: 2.4,
    expiresAtMs: now + 55 * 60 * 1000, startedAtMs: now - 5 * 60 * 1000,
    lat: 51.5220, lng: -0.0760,
  },
  {
    id: 'demo-session-5',
    userId: 'demo-user-5',
    displayName: 'Isabelle', age: 31,
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk6.png',
    gender: 'female',
    bio: 'Coffee snob by day, gin lover by night ☕',
    activityType: 'cinema',
    activities: ['cinema', 'cocktails', 'coffee'],
    lookingFor: 'Dating',
    area: 'Hyde Park', city: 'London',
    status: 'active', venueId: 'venue-bloomsbury-pub',
    distanceKm: 1.8,
    expiresAtMs: now + 20 * 60 * 1000, startedAtMs: now - 40 * 60 * 1000,
    lat: 51.5064, lng: -0.1732,
  },
  {
    id: 'demo-session-6',
    userId: 'demo-user-6',
    displayName: 'Amelia', age: 28,
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk8.png',
    gender: 'female',
    bio: 'Brunch enthusiast. Will judge you by your coffee order ☕',
    activityType: 'fastfood',
    activities: ['fastfood', 'cocktails', 'coffee'],
    lookingFor: 'Dating',
    area: 'Camden', city: 'London',
    status: 'active', venueId: 'venue-soho-bar', tier: 'boost',
    distanceKm: 3.2,
    expiresAtMs: now + 75 * 60 * 1000, startedAtMs: now - 5 * 60 * 1000,
    lat: 51.5390, lng: -0.1426,
  },
  {
    id: 'demo-session-8',
    userId: 'demo-user-10',
    displayName: 'Mia', age: 29,
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk7.png',
    gender: 'female',
    bio: 'Wine and pintxos kind of evening 🍷',
    activityType: 'wine',
    activities: ['wine', 'pizza'],
    lookingFor: 'Dating',
    area: 'Fitzrovia', city: 'London',
    status: 'active', venueId: 'partner-barrica', distanceKm: 0.9,
    expiresAtMs: now + 45 * 60 * 1000, startedAtMs: now - 20 * 60 * 1000,
    lat: 51.5196, lng: -0.1357,
  },
]

// Hide active sessions after midnight UK time
export const DEMO_SESSIONS = _isUKLateNight ? [] : _ACTIVE_SESSIONS

// Scheduled sessions — "I'm Out Later"
// scheduledFor = ms timestamp when they go live
function tonight(hour, minute = 0) {
  const d = new Date(); d.setHours(hour, minute, 0, 0)
  if (d.getTime() < Date.now()) d.setDate(d.getDate() + 1)
  return d.getTime()
}
function tomorrow(hour, minute = 0) {
  const d = new Date(); d.setDate(d.getDate() + 1); d.setHours(hour, minute, 0, 0)
  return d.getTime()
}

export const DEMO_SCHEDULED_SESSIONS = [
  {
    id: 'demo-sched-1', userId: 'demo-user-7',
    displayName: 'Poppy', age: 26,
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk9.png',
    gender: 'female',
    bio: 'Looking for someone to explore the city with 🗺️',
    activityType: 'drinks',
    activities: ['drinks', 'food', 'hangout'],
    lookingFor: 'Dating',
    area: 'Soho', city: 'London',
    distanceKm: 0.7,
    status: 'scheduled', scheduledFor: tonight(20, 0),
    expiresAtMs: tonight(20, 0) + 120 * 60 * 1000, startedAtMs: null,
    ...offset(300, 700),
  },
  {
    id: 'demo-sched-2', userId: 'demo-user-8',
    displayName: 'Grace', age: 30,
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk10.png',
    photos: ['https://ik.imagekit.io/nepgaxllc/uk10.png', 'https://ik.imagekit.io/nepgaxllc/Untitleddfsdf.png', 'https://ik.imagekit.io/nepgaxllc/Untitleddfsdfss.png', 'https://ik.imagekit.io/nepgaxllc/Untitleddfsdfssxczxcsss.png'],
    gender: 'female',
    bio: 'Film nights and good restaurants. Simple pleasures 🎬',
    activityType: 'walk',
    activities: ['walk', 'hiking', 'culture'],
    lookingFor: 'Dating',
    area: 'Shoreditch', city: 'London',
    distanceKm: 1.4,
    status: 'scheduled', scheduledFor: tonight(19, 30),
    expiresAtMs: tonight(19, 30) + 90 * 60 * 1000, startedAtMs: null,
    ...offset(400, 800),
  },
  {
    id: 'demo-sched-3', userId: 'demo-user-9',
    displayName: 'Harriet', age: 24,
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk3.png',
    gender: 'female',
    bio: 'Cinema then cocktails — best evening ever 🍸',
    activityType: 'culture',
    activities: ['culture', 'coffee', 'drinks'],
    lookingFor: 'Dating',
    area: 'Leicester Sq', city: 'London',
    distanceKm: 2.2,
    status: 'scheduled', scheduledFor: tomorrow(18, 0),
    expiresAtMs: tomorrow(18, 0) + 150 * 60 * 1000, startedAtMs: null,
    ...offset(200, 500),
  },
]

export const DEMO_INVITE_OUT_SESSIONS = [
  {
    id: 'demo-invite-2', userId: 'demo-user-11',
    isSeeded: true,
    userJoinedAt: new Date('2025-10-03').getTime(),
    displayName: 'Daisy', age: 29,
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk4.png',
    gender: 'female',
    bio: 'Obsessed with finding hidden gem restaurants 🍝',
    activityType: 'food',
    activities: ['food', 'drinks', 'culture'],
    lookingFor: 'dating',
    relationshipGoal: 'open',
    starSign: 'Libra',
    height: '5\'6"',
    area: 'Soho', city: 'London',
    distanceKm: 1.9,
    status: 'invite_out',
    message: 'Looking for somewhere good to eat tonight',
    ...offset(200, 600),
  },
  {
    id: 'demo-invite-3', userId: 'demo-user-12',
    isSeeded: true,
    userJoinedAt: new Date('2025-11-20').getTime(),
    displayName: 'Freya', age: 24,
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk6.png',
    gender: 'female',
    bio: 'Morning runs, afternoon coffee, evening adventures ☕',
    activityType: 'coffee',
    activities: ['coffee', 'walk', 'hangout'],
    lookingFor: 'Dating',
    area: 'Covent Garden', city: 'London',
    distanceKm: 0.3,
    status: 'invite_out',
    message: 'Free this afternoon if anyone wants to explore',
    ...offset(400, 800),
  },
  {
    id: 'demo-invite-4', userId: 'demo-user-13',
    isSeeded: true,
    userJoinedAt: new Date('2026-01-07').getTime(),
    displayName: 'Imogen', age: 32,
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk9.png',
    gender: 'female',
    bio: 'Park walks and good conversation — my kind of date 🌿',
    activityType: 'walk',
    activities: ['walk', 'coffee', 'food'],
    lookingFor: 'Dating',
    area: 'Hyde Park', city: 'London',
    distanceKm: 2.8,
    status: 'invite_out',
    message: 'Up for a walk if anyone is around',
    ...offset(500, 900),
  },
  {
    id: 'demo-invite-5', userId: 'demo-user-14',
    isSeeded: true,
    userJoinedAt: new Date('2026-02-19').getTime(),
    displayName: 'Rosie', age: 27,
    photoURL: 'https://ik.imagekit.io/nepgaxllc/uk10.png',
    gender: 'female',
    bio: 'Gin & tonic in hand, ready for a great night 🥂',
    activityType: 'drinks',
    activities: ['drinks', 'food', 'hangout'],
    lookingFor: 'Dating',
    distanceKm: 1.1,
    area: 'Camden', city: 'London',
    status: 'invite_out',
    message: 'Anyone else out in Camden tonight?',
    ...offset(300, 650),
  },
]

// ── Indonesian maker / handmade sessions — used for city search demo ──────────
export const DEMO_MAKER_SESSIONS = [
  // Jakarta — 5 sessions
  {
    id: 'maker-jkt-1', userId: 'maker-user-1',
    displayName: 'Sari', age: 28,
    photoURL: 'https://picsum.photos/seed/bag1/400/300',
    priceFrom: '350.000', priceTo: '1.200.000',
    instagram: 'saribagsstudio', tiktok: 'saribags', facebook: '', website: 'https://saribags.id',
    isVerified: true,
    brandName: 'Sari Bags Studio',
    bio: 'Handcrafted leather handbags made to order. Based in Jakarta Selatan.',
    activityType: 'handbags', activities: ['handbags'],
    productWord: 'Handbag', sellerType: 'Maker',
    lookingFor: 'handmade',
    tags: ['handbags', 'leather bags', 'custom bags', 'jakarta bags'],
    area: 'Jakarta Selatan', city: 'Jakarta', country: 'Indonesia',
    status: 'active',
    lat: -6.2607, lng: 106.8107,
    fuzzedLat: -6.2607, fuzzedLng: 106.8107,
    distanceKm: 2.1, expiresAtMs: now + 60 * 60 * 1000, startedAtMs: now - 20 * 60 * 1000,
  },
  {
    id: 'maker-jkt-2', userId: 'maker-user-2',
    displayName: 'Dewi', age: 32,
    photoURL: 'https://picsum.photos/seed/bag2/400/300',
    priceFrom: '580.000', priceTo: '2.500.000',
    instagram: 'dewileatherco', tiktok: 'dewileather', facebook: 'DewíLeatherCo', website: '',
    isVerified: true,
    brandName: 'Dewi Leather Co',
    bio: 'Premium leather goods — handbags, wallets, belts. Custom orders welcome.',
    activityType: 'handbags', activities: ['handbags', 'leatherwork'],
    productWord: 'Leather', sellerType: 'Maker',
    lookingFor: 'handmade',
    tags: ['handbags', 'leather', 'wallets', 'wholesale'],
    area: 'Kemang', city: 'Jakarta', country: 'Indonesia',
    status: 'active',
    lat: -6.2567, lng: 106.8130,
    fuzzedLat: -6.2567, fuzzedLng: 106.8130,
    distanceKm: 1.8, expiresAtMs: now + 90 * 60 * 1000, startedAtMs: now - 10 * 60 * 1000,
  },
  {
    id: 'maker-jkt-3', userId: 'maker-user-3',
    displayName: 'Rina', age: 25,
    photoURL: 'https://picsum.photos/seed/bag3/400/300',
    priceFrom: '220.000', priceTo: '850.000',
    instagram: 'rinacrafthouse', tiktok: '', facebook: 'RinaCraftHouse', website: '',
    isVerified: true,
    brandName: 'Rina Craft House',
    bio: 'Woven rattan and fabric bags. Eco-friendly materials only.',
    activityType: 'handbags', activities: ['handbags', 'craft'],
    productWord: 'Rattan', sellerType: 'Maker',
    lookingFor: 'handmade',
    tags: ['handbags', 'rattan', 'eco bags', 'woven bags'],
    area: 'Menteng', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out',
    message: 'Available today to meet buyers and retailers',
    lat: -6.1942, lng: 106.8321,
    fuzzedLat: -6.1942, fuzzedLng: 106.8321,
    distanceKm: 3.4, expiresAtMs: now + 120 * 60 * 1000, startedAtMs: null,
  },
  {
    id: 'maker-jkt-4', userId: 'maker-user-4',
    displayName: 'Putri', age: 30,
    photoURL: 'https://picsum.photos/seed/bag4/400/300',
    priceFrom: '420.000', priceTo: '1.800.000',
    instagram: 'putribatikbags', tiktok: '', facebook: '', website: 'https://putribatik.com',
    isVerified: true,
    brandName: 'Putri Batik Bags',
    bio: 'Traditional batik handbags and totes. Unique Indonesian designs.',
    activityType: 'handbags', activities: ['handbags', 'textile_art'],
    productWord: 'Batik', sellerType: 'Seller',
    lookingFor: 'handmade',
    tags: ['handbags', 'batik', 'tote bags', 'traditional'],
    area: 'Senayan', city: 'Jakarta', country: 'Indonesia',
    status: 'scheduled', scheduledFor: tonight(14, 0),
    lat: -6.2183, lng: 106.8025,
    fuzzedLat: -6.2183, fuzzedLng: 106.8025,
    distanceKm: 2.7, expiresAtMs: tonight(14, 0) + 180 * 60 * 1000, startedAtMs: null,
  },
  {
    id: 'maker-jkt-5', userId: 'maker-user-5',
    displayName: 'Nisa', age: 27,
    photoURL: 'https://picsum.photos/seed/bag5/400/300',
    priceFrom: '680.000', priceTo: '3.200.000',
    brandName: 'Nisa Accessories',
    bio: 'Handmade beaded bags and clutches for events and weddings.',
    activityType: 'handbags', activities: ['handbags', 'jewellery'],
    productWord: 'Clutch', sellerType: 'Maker',
    lookingFor: 'handmade',
    tags: ['handbags', 'clutch', 'beaded bags', 'wedding bags'],
    area: 'Pluit', city: 'Jakarta', country: 'Indonesia',
    status: 'active',
    lat: -6.1230, lng: 106.7986,
    fuzzedLat: -6.1230, fuzzedLng: 106.7986,
    distanceKm: 4.1, expiresAtMs: now + 75 * 60 * 1000, startedAtMs: now - 5 * 60 * 1000,
  },

  // Bali — 4 sessions
  {
    id: 'maker-bali-1', userId: 'maker-user-6',
    displayName: 'Kadek', age: 29,
    photoURL: 'https://picsum.photos/seed/bag6/400/300',
    priceFrom: '290.000', priceTo: '950.000',
    brandName: 'Bali Boho Bags',
    bio: 'Boho-style handwoven bags. Wholesale available for boutiques.',
    activityType: 'handbags', activities: ['handbags', 'craft'],
    productWord: 'Boho', sellerType: 'Maker',
    lookingFor: 'handmade',
    tags: ['handbags', 'boho bags', 'bali style', 'wholesale'],
    area: 'Seminyak', city: 'Bali', country: 'Indonesia',
    status: 'active',
    lat: -8.6915, lng: 115.1686,
    fuzzedLat: -8.6915, fuzzedLng: 115.1686,
    distanceKm: 1.2, expiresAtMs: now + 60 * 60 * 1000, startedAtMs: now - 30 * 60 * 1000,
  },
  {
    id: 'maker-bali-2', userId: 'maker-user-7',
    displayName: 'Made', age: 35,
    photoURL: 'https://picsum.photos/seed/bag7/400/300',
    priceFrom: '750.000', priceTo: '4.500.000',
    brandName: 'Made Leather Bali',
    bio: 'Artisan leather bags crafted in Ubud. Export quality.',
    activityType: 'handbags', activities: ['handbags', 'leatherwork'],
    productWord: 'Leather', sellerType: 'Maker',
    lookingFor: 'handmade',
    tags: ['handbags', 'leather', 'ubud craft', 'export'],
    area: 'Ubud', city: 'Bali', country: 'Indonesia',
    status: 'invite_out',
    message: 'Open for meetings with buyers this week',
    lat: -8.5069, lng: 115.2625,
    fuzzedLat: -8.5069, fuzzedLng: 115.2625,
    distanceKm: 5.3, expiresAtMs: now + 180 * 60 * 1000, startedAtMs: null,
  },
  {
    id: 'maker-bali-3', userId: 'maker-user-8',
    displayName: 'Wayan', age: 31,
    photoURL: 'https://picsum.photos/seed/bag8/400/300',
    priceFrom: '185.000', priceTo: '650.000',
    brandName: 'Wayan Rattan Works',
    bio: 'Handmade rattan and bamboo bags. Sustainable sourcing.',
    activityType: 'handbags', activities: ['handbags'],
    productWord: 'Rattan', sellerType: 'Seller',
    lookingFor: 'handmade',
    tags: ['handbags', 'rattan', 'bamboo bags', 'sustainable'],
    area: 'Canggu', city: 'Bali', country: 'Indonesia',
    status: 'active',
    lat: -8.6478, lng: 115.1385,
    fuzzedLat: -8.6478, fuzzedLng: 115.1385,
    distanceKm: 3.8, expiresAtMs: now + 45 * 60 * 1000, startedAtMs: now - 15 * 60 * 1000,
  },
  {
    id: 'maker-bali-4', userId: 'maker-user-9',
    displayName: 'Ayu', age: 26,
    photoURL: 'https://picsum.photos/seed/bag9/400/300',
    priceFrom: '310.000', priceTo: '1.100.000',
    brandName: 'Ayu Bag Studio',
    bio: 'Fabric patchwork and ikat bags. Unique handmade designs.',
    activityType: 'handbags', activities: ['handbags', 'sewing'],
    productWord: 'Ikat', sellerType: 'Maker',
    lookingFor: 'handmade',
    tags: ['handbags', 'ikat', 'patchwork', 'fabric bags'],
    area: 'Kuta', city: 'Bali', country: 'Indonesia',
    status: 'scheduled', scheduledFor: tonight(10, 0),
    lat: -8.7215, lng: 115.1700,
    fuzzedLat: -8.7215, fuzzedLng: 115.1700,
    distanceKm: 2.5, expiresAtMs: tonight(10, 0) + 120 * 60 * 1000, startedAtMs: null,
  },

  // Surabaya — 3 sessions
  {
    id: 'maker-sby-1', userId: 'maker-user-10',
    displayName: 'Indah', age: 33,
    photoURL: 'https://picsum.photos/seed/bag10/400/300',
    priceFrom: '450.000', priceTo: '2.000.000',
    brandName: 'Indah Handbag Factory',
    bio: 'Manufacturer of women\'s handbags. Minimum order 10 pieces.',
    activityType: 'handbags', activities: ['handbags'],
    productWord: 'Handbag', sellerType: 'Seller',
    lookingFor: 'handmade',
    tags: ['handbags', 'manufacturer', 'wholesale', 'surabaya'],
    area: 'Rungkut', city: 'Surabaya', country: 'Indonesia',
    status: 'active',
    lat: -7.3232, lng: 112.7706,
    fuzzedLat: -7.3232, fuzzedLng: 112.7706,
    distanceKm: 3.1, expiresAtMs: now + 60 * 60 * 1000, startedAtMs: now - 25 * 60 * 1000,
  },
  {
    id: 'maker-sby-2', userId: 'maker-user-11',
    displayName: 'Sri', age: 40,
    photoURL: 'https://picsum.photos/seed/bag11/400/300',
    priceFrom: '620.000', priceTo: '3.800.000',
    brandName: 'Sri Classic Bags',
    bio: 'Classic leather handbags and briefcases. Family business since 2005.',
    activityType: 'handbags', activities: ['handbags', 'leatherwork'],
    productWord: 'Briefcase', sellerType: 'Seller',
    lookingFor: 'handmade',
    tags: ['handbags', 'briefcase', 'leather', 'classic'],
    area: 'Genteng', city: 'Surabaya', country: 'Indonesia',
    status: 'invite_out',
    message: 'Looking for retail partners in Surabaya',
    lat: -7.2575, lng: 112.7521,
    fuzzedLat: -7.2575, fuzzedLng: 112.7521,
    distanceKm: 1.9, expiresAtMs: now + 90 * 60 * 1000, startedAtMs: null,
  },
  {
    id: 'maker-sby-3', userId: 'maker-user-12',
    displayName: 'Lestari', age: 24,
    photoURL: 'https://picsum.photos/seed/bag12/400/300',
    priceFrom: '95.000', priceTo: '380.000',
    bio: 'Mini bags and coin purses — kawaii style. Online & meet in person.',
    activityType: 'handbags', activities: ['handbags', 'sewing'],
    productWord: 'Purse', sellerType: 'Maker',
    lookingFor: 'handmade',
    tags: ['handbags', 'mini bags', 'coin purse', 'kawaii'],
    area: 'Gubeng', city: 'Surabaya', country: 'Indonesia',
    status: 'active',
    lat: -7.2714, lng: 112.7527,
    fuzzedLat: -7.2714, fuzzedLng: 112.7527,
    distanceKm: 0.8, expiresAtMs: now + 50 * 60 * 1000, startedAtMs: now - 8 * 60 * 1000,
  },

  // Bandung — 2 sessions
  {
    id: 'maker-bdg-1', userId: 'maker-user-13',
    displayName: 'Tari', age: 29,
    photoURL: 'https://picsum.photos/seed/bag13/400/300',
    priceFrom: '275.000', priceTo: '900.000',
    brandName: 'Tari Denim Bags',
    bio: 'Upcycled denim handbags. Every piece is one of a kind.',
    activityType: 'handbags', activities: ['handbags', 'upcycling'],
    productWord: 'Denim', sellerType: 'Maker',
    lookingFor: 'handmade',
    tags: ['handbags', 'denim bags', 'upcycled', 'sustainable'],
    area: 'Dago', city: 'Bandung', country: 'Indonesia',
    status: 'active',
    lat: -6.8798, lng: 107.6125,
    fuzzedLat: -6.8798, fuzzedLng: 107.6125,
    distanceKm: 2.3, expiresAtMs: now + 70 * 60 * 1000, startedAtMs: now - 12 * 60 * 1000,
  },
  {
    id: 'maker-bdg-2', userId: 'maker-user-14',
    displayName: 'Mega', age: 27,
    photoURL: 'https://picsum.photos/seed/bag14/400/300',
    priceFrom: '380.000', priceTo: '1.500.000',
    brandName: 'Mega Tenun Bags',
    bio: 'Traditional tenun woven bags from West Java. Export quality.',
    activityType: 'handbags', activities: ['handbags', 'textile_art'],
    productWord: 'Tenun', sellerType: 'Maker',
    lookingFor: 'handmade',
    tags: ['handbags', 'tenun', 'woven', 'west java'],
    area: 'Buah Batu', city: 'Bandung', country: 'Indonesia',
    status: 'invite_out',
    message: 'Available to meet buyers and boutique owners',
    lat: -6.9509, lng: 107.6399,
    fuzzedLat: -6.9509, fuzzedLng: 107.6399,
    distanceKm: 4.2, expiresAtMs: now + 100 * 60 * 1000, startedAtMs: null,
  },

  // Medan — 2 sessions
  {
    id: 'maker-mdn-1', userId: 'maker-user-15',
    displayName: 'Aisyah', age: 31,
    photoURL: 'https://picsum.photos/seed/bag15/400/300',
    priceFrom: '520.000', priceTo: '2.800.000',
    brandName: 'Aisyah Songket Bags',
    bio: 'Songket fabric handbags. Traditional North Sumatran craft.',
    activityType: 'handbags', activities: ['handbags', 'textile_art'],
    productWord: 'Songket', sellerType: 'Maker',
    lookingFor: 'handmade',
    tags: ['handbags', 'songket', 'sumatra craft', 'traditional'],
    area: 'Medan Baru', city: 'Medan', country: 'Indonesia',
    status: 'active',
    lat: 3.5880, lng: 98.6722,
    fuzzedLat: 3.5880, fuzzedLng: 98.6722,
    distanceKm: 1.6, expiresAtMs: now + 80 * 60 * 1000, startedAtMs: now - 18 * 60 * 1000,
  },
  {
    id: 'maker-mdn-2', userId: 'maker-user-16',
    displayName: 'Fitri', age: 25,
    photoURL: 'https://picsum.photos/seed/bag16/400/300',
    priceFrom: '150.000', priceTo: '480.000',
    bio: 'Handmade bags using recycled flour sacks. Eco fashion.',
    activityType: 'handbags', activities: ['handbags', 'upcycling'],
    productWord: 'Eco', sellerType: 'Maker',
    lookingFor: 'handmade',
    tags: ['handbags', 'recycled', 'eco fashion', 'upcycled bags'],
    area: 'Helvetia', city: 'Medan', country: 'Indonesia',
    status: 'active',
    lat: 3.6194, lng: 98.6388,
    fuzzedLat: 3.6194, fuzzedLng: 98.6388,
    distanceKm: 2.9, expiresAtMs: now + 55 * 60 * 1000, startedAtMs: now - 22 * 60 * 1000,
  },
  {
    id: 'maker-jkt-6', userId: 'maker-user-17',
    displayName: 'Citra', age: 29,
    photoURL: 'https://picsum.photos/seed/bag17/400/300',
    priceFrom: '890.000', priceTo: '5.000.000',
    bio: 'Luxury tote bags made from batik fabric. Ships worldwide.',
    activityType: 'handbags', activities: ['handbags', 'fashion_design'],
    productWord: 'Tote', sellerType: 'Seller',
    lookingFor: 'handmade',
    tags: ['handbags', 'batik', 'luxury', 'tote'],
    area: 'Kemang', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out',
    lat: -6.2603, lng: 106.8147,
    fuzzedLat: -6.2603, fuzzedLng: 106.8147,
    distanceKm: 1.4, expiresAtMs: now + 70 * 60 * 1000, startedAtMs: now - 10 * 60 * 1000,
  },
  {
    id: 'maker-jkt-7', userId: 'maker-user-18',
    displayName: 'Lina', age: 31,
    photoURL: 'https://picsum.photos/seed/bag18/400/300',
    priceFrom: '430.000', priceTo: '1.600.000',
    bio: 'Minimalist leather clutch bags. Custom orders welcome.',
    activityType: 'leatherwork', activities: ['leatherwork', 'handbags'],
    productWord: 'Clutch', sellerType: 'Maker',
    lookingFor: 'handmade',
    tags: ['leather', 'clutch', 'minimalist', 'custom'],
    area: 'Senayan', city: 'Jakarta', country: 'Indonesia',
    status: 'active',
    lat: -6.2297, lng: 106.8011,
    fuzzedLat: -6.2297, fuzzedLng: 106.8011,
    distanceKm: 2.1, expiresAtMs: now + 40 * 60 * 1000, startedAtMs: now - 30 * 60 * 1000,
  },
  {
    id: 'maker-bali-5', userId: 'maker-user-19',
    displayName: 'Ni Made', age: 27,
    photoURL: 'https://picsum.photos/seed/bag19/400/300',
    priceFrom: '340.000', priceTo: '1.200.000',
    bio: 'Woven rattan bags inspired by Balinese craft tradition.',
    activityType: 'handbags', activities: ['handbags', 'craft'],
    lookingFor: 'handmade',
    tags: ['rattan', 'woven', 'balinese', 'bags'],
    area: 'Ubud', city: 'Bali', country: 'Indonesia',
    status: 'scheduled',
    lat: -8.5069, lng: 115.2625,
    fuzzedLat: -8.5069, fuzzedLng: 115.2625,
    distanceKm: 3.2, expiresAtMs: now + 90 * 60 * 1000, startedAtMs: now - 5 * 60 * 1000,
  },
  {
    id: 'maker-sby-4', userId: 'maker-user-20',
    displayName: 'Hana', age: 26,
    photoURL: 'https://picsum.photos/seed/bag20/400/300',
    priceFrom: '260.000', priceTo: '780.000',
    bio: 'Embroidered shoulder bags with floral patterns. Each piece unique.',
    activityType: 'handbags', activities: ['handbags', 'embroidery'],
    lookingFor: 'handmade',
    tags: ['embroidery', 'shoulder bag', 'floral', 'handmade'],
    area: 'Gubeng', city: 'Surabaya', country: 'Indonesia',
    status: 'active',
    lat: -7.2658, lng: 112.7509,
    fuzzedLat: -7.2658, fuzzedLng: 112.7509,
    distanceKm: 1.8, expiresAtMs: now + 50 * 60 * 1000, startedAtMs: now - 15 * 60 * 1000,
  },
  {
    id: 'maker-jkt-8', userId: 'maker-user-21',
    displayName: 'Vina', age: 28,
    photoURL: 'https://picsum.photos/seed/bag21/400/300',
    priceFrom: '310.000', priceTo: '1.050.000',
    bio: 'Hand-painted canvas bags. Bold colours, limited runs.',
    activityType: 'handbags', activities: ['handbags', 'fashion_design'],
    lookingFor: 'handmade',
    tags: ['canvas', 'painted', 'limited edition', 'bags'],
    area: 'Menteng', city: 'Jakarta', country: 'Indonesia',
    status: 'active',
    lat: -6.1944, lng: 106.8294,
    fuzzedLat: -6.1944, fuzzedLng: 106.8294,
    distanceKm: 1.1, expiresAtMs: now + 60 * 60 * 1000, startedAtMs: now - 8 * 60 * 1000,
  },
  {
    id: 'maker-jkt-9', userId: 'maker-user-22',
    displayName: 'Rara', age: 24,
    photoURL: 'https://picsum.photos/seed/bag22/400/300',
    priceFrom: '560.000', priceTo: '2.200.000',
    bio: 'Beaded evening bags. Perfect for weddings and events.',
    activityType: 'handbags', activities: ['handbags', 'jewellery'],
    lookingFor: 'handmade',
    tags: ['beaded', 'evening bag', 'wedding', 'handmade'],
    area: 'Sudirman', city: 'Jakarta', country: 'Indonesia',
    status: 'invite_out',
    lat: -6.2088, lng: 106.8175,
    fuzzedLat: -6.2088, fuzzedLng: 106.8175,
    distanceKm: 0.9, expiresAtMs: now + 80 * 60 * 1000, startedAtMs: now - 20 * 60 * 1000,
  },
  // ── UK maker — always visible regardless of time ──────────────────────────
  {
    id: 'demo-session-7',
    userId: 'demo-user-9',
    displayName: 'Zara', age: 26,
    photoURL: null,
    photos: ['https://ik.imagekit.io/nepgaxllc/Untitledsdfasdfddd.png', 'https://ik.imagekit.io/nepgaxllc/Untitledsdfasdfdddfsdfsd.png'],
    isVerified: true,
    brandName: 'Zara Clothes',
    tradeRole: 'both',
    priceFrom: '12.000', priceTo: '24.000',
    speakingNative: 'Indonesian',
    speakingSecond: 'English',
    market: 'Local & Export',
    gender: 'female',
    bio: 'Designer and fabric maker for shoes and hats. Contact me for any request.',
    activityType: 'dress_making',
    activities: ['dress_making', 'fashion_design', 'sewing'],
    lookingFor: 'handmade',
    tags: ['clothes', 'dress', 'fashion', 'sewing', 'handmade'],
    tier: 'listing',
    instagram: 'zaraclothesuk', tiktok: 'zaraclothes', facebook: 'ZaraClothesLondon', youtube: 'zaraclothesuk', website: 'https://zaraclothes.co.uk',
    area: 'Soho', city: 'London', country: 'United Kingdom',
    status: 'active',
    lat: 51.5133, lng: -0.1320,
    fuzzedLat: 51.5133, fuzzedLng: -0.1320,
    distanceKm: 0.4, expiresAtMs: now + 60 * 60 * 1000, startedAtMs: now - 10 * 60 * 1000,
  },
]

export const DEMO_REVIEWS = [
  {
    id: 'r1',
    displayName: 'Isabelle M.',
    emoji: '😊',
    age: 27,
    area: 'Soho, London',
    country: 'GB',
    flag: '🇬🇧',
    rating: 5,
    text: 'Met someone incredible within 20 minutes of going live. We ended up staying at the bar for 3 hours. This app is genuinely different — no awkward texting, just real chemistry in person.',
    activityType: 'drinks',
    verified: true,
    timeAgo: '2 days ago',
  },
  {
    id: 'r2',
    displayName: 'James T.',
    emoji: '😎',
    age: 31,
    area: 'Shoreditch, London',
    country: 'GB',
    flag: '🇬🇧',
    rating: 5,
    text: 'Refreshing concept. No endless swiping, no ghosting. Hit the button, someone nearby was also out, we grabbed coffee. Simple as that.',
    activityType: 'coffee',
    verified: true,
    timeAgo: '4 days ago',
  },
  {
    id: 'r3',
    displayName: 'Priya K.',
    emoji: '✨',
    age: 25,
    area: 'Notting Hill, London',
    country: 'GB',
    flag: '🇬🇧',
    rating: 5,
    text: 'Finally an app that feels safe. No random messages from strangers — just people who are actually nearby and actually out. The female safety features are a massive plus.',
    activityType: 'food',
    verified: true,
    timeAgo: '1 week ago',
  },
  {
    id: 'r4',
    displayName: 'Marcus O.',
    emoji: '🎯',
    age: 29,
    area: 'Camden, London',
    country: 'GB',
    flag: '🇬🇧',
    rating: 4,
    text: 'Third time using it this week — matched twice and met once. The vibe is totally different to Tinder. People are actually there and ready to meet. Love the Out Later feature for planning weekends.',
    activityType: 'hangout',
    verified: false,
    timeAgo: '3 days ago',
  },
  {
    id: 'r5',
    displayName: 'Sophie R.',
    emoji: '🌸',
    age: 24,
    area: 'Brixton, London',
    country: 'GB',
    flag: '🇬🇧',
    rating: 5,
    text: 'The 10-minute chat window is genius. Forces you to actually go meet them instead of chatting forever. Went on two spontaneous dates this month.',
    activityType: 'drinks',
    verified: true,
    timeAgo: '5 days ago',
  },
]

export const DEMO_CENTER = { lat: BASE_LAT, lng: BASE_LNG }

// Chat statuses:
//  'unlocked' — both paid, full chat open
//  'locked'   — I received a message but haven't paid to read/reply
//  'pending'  — I sent my free first message, waiting for them to unlock
//  'free'     — no messages yet, I can send 1 free message
export const DEMO_CONVERSATIONS = [
  {
    id: 'conv-1',
    userId: 'demo-user-1',
    displayName: 'Jordan',
    emoji: '😎',
    age: 29,
    online: true,
    status: 'unlocked',
    openedAt: now - 4 * 60 * 1000,
    unlockedAt: now - 4 * 60 * 1000,
    lastMessage: 'Which bar are you at now?',
    lastMessageTime: now - 5 * 60 * 1000,
    unread: 1,
    messages: [
      { id: 'm1', fromMe: false, text: 'Hey! Saw you were out in Soho 👋', time: now - 25 * 60 * 1000 },
      { id: 'm2', fromMe: true,  text: 'Yeah! At The Slug & Lettuce', time: now - 22 * 60 * 1000 },
      { id: 'm3', fromMe: false, text: "Nice, I'm nearby. Which bar are you at now?", time: now - 5 * 60 * 1000 },
    ],
  },
  {
    id: 'conv-2',
    userId: 'demo-user-2',
    displayName: 'Ava',
    emoji: '😊',
    age: 26,
    online: true,
    status: 'locked',
    lastMessage: '🔒 Unlock to read',
    lastMessageTime: now - 18 * 60 * 1000,
    unread: 1,
    messages: [],
  },
  {
    id: 'conv-3',
    userId: 'demo-user-3',
    displayName: 'Kai',
    emoji: '🤙',
    age: 28,
    online: false,
    status: 'pending',
    lastMessage: 'You around Dalston tonight?',
    lastMessageTime: now - 45 * 60 * 1000,
    unread: 0,
    messages: [
      { id: 'm1', fromMe: true, text: 'You around Dalston tonight?', time: now - 45 * 60 * 1000 },
    ],
  },
  {
    id: 'conv-4',
    userId: 'demo-user-4',
    displayName: 'Sofia',
    emoji: '✨',
    age: 23,
    online: true,
    status: 'free',
    lastMessage: null,
    lastMessageTime: null,
    unread: 0,
    messages: [],
  },
]

export const DEMO_MATCH_PROFILES = [
  {
    id: 'p1', displayName: 'Sarah', age: 29, emoji: '😊', gender: 'Woman',
    online: true, distanceKm: 2.1, readyToMeet: true, verified: true,
    tagline: 'Coffee and a good walk? Yes please.',
    area: 'Soho', lookingFor: 'Date', availability: 'Tonight',
    meetSpeed: 'Meet now', firstMeet: ['Coffee', 'Walk'],
    responseTime: '< 5 min', liked: false,
  },
  {
    id: 'p2', displayName: 'Marcus', age: 31, emoji: '😎', gender: 'Man',
    online: true, distanceKm: 0.8, readyToMeet: true, verified: true,
    tagline: 'Free this evening. Drinks?',
    area: 'Shoreditch', lookingFor: 'Meet now', availability: 'Tonight',
    meetSpeed: 'Meet now', firstMeet: ['Drinks', 'Dinner'],
    responseTime: '< 10 min', liked: false,
  },
  {
    id: 'p3', displayName: 'Zoe', age: 25, emoji: '🌸', gender: 'Woman',
    online: false, distanceKm: 3.4, readyToMeet: false, verified: false,
    tagline: 'Let\'s find the best coffee spot.',
    area: 'Camden', lookingFor: 'Chat', availability: 'Today',
    meetSpeed: 'Today', firstMeet: ['Coffee'],
    responseTime: '~30 min', liked: false,
  },
  {
    id: 'p4', displayName: 'Kai', age: 27, emoji: '🤙', gender: 'Man',
    online: true, distanceKm: 1.2, readyToMeet: true, verified: true,
    tagline: 'Spontaneous plans only.',
    area: 'Dalston', lookingFor: 'Meet now', availability: 'Tonight',
    meetSpeed: 'Meet now', firstMeet: ['Drinks', 'Walk'],
    responseTime: '< 5 min', liked: false,
  },
  {
    id: 'p5', displayName: 'Priya', age: 26, emoji: '✨', gender: 'Woman',
    online: true, distanceKm: 4.7, readyToMeet: false, verified: true,
    tagline: 'Art, food, good conversation.',
    area: 'Notting Hill', lookingFor: 'Date', availability: 'Weekend',
    meetSpeed: 'This week', firstMeet: ['Dinner', 'Coffee'],
    responseTime: '~1 hr', liked: false,
  },
  {
    id: 'p6', displayName: 'Finn', age: 30, emoji: '🎯', gender: 'Man',
    online: false, distanceKm: 2.9, readyToMeet: true, verified: false,
    tagline: 'Drinks after work — who\'s in?',
    area: 'Brixton', lookingFor: 'Chat', availability: 'Tonight',
    meetSpeed: 'Today', firstMeet: ['Drinks'],
    responseTime: '~20 min', liked: false,
  },
]

// Venue group chat demo messages — keyed by venueId
export const DEMO_VENUE_MESSAGES = {
  'venue-soho-bar': [
    { id: 'vm-1', userId: 'demo-user-1', displayName: 'Jordan', text: "Just got here — it's absolutely packed tonight 🔥", createdAt: now - 18 * 60 * 1000 },
    { id: 'vm-2', userId: 'demo-user-2', displayName: 'Mia',    text: "Same! Grabbed a table near the back 👋", createdAt: now - 15 * 60 * 1000 },
    { id: 'vm-3', userId: 'demo-user-6', displayName: 'Leo',    text: "On my way — 5 mins out", createdAt: now - 12 * 60 * 1000 },
    { id: 'vm-4', userId: 'demo-user-2', displayName: 'Mia',    text: "Live band just started, vibes are unreal 🎶", createdAt: now - 8 * 60 * 1000 },
    { id: 'vm-5', userId: 'demo-user-6', displayName: 'Leo',    text: "Here now — bar is crazy busy, getting drinks first", createdAt: now - 4 * 60 * 1000 },
    { id: 'vm-6', userId: 'demo-user-1', displayName: 'Jordan', text: "Someone save us a spot 😂", createdAt: now - 2 * 60 * 1000 },
  ],
  'venue-fitz-bistro': [
    { id: 'vm-7', userId: 'demo-user-3', displayName: 'Raf', text: "Wine is excellent tonight — 2 for 1 still on 🍷", createdAt: now - 20 * 60 * 1000 },
    { id: 'vm-8', userId: 'demo-user-3', displayName: 'Raf', text: "Anyone else coming here tonight?", createdAt: now - 6 * 60 * 1000 },
  ],
}

// Ephemeral moments — disappear after 6 hours
// In demo, gradient + emoji replace real photos
export const DEMO_MOMENTS = [
  {
    id: 'moment-1',
    userId: 'demo-user-2',
    displayName: 'Mia',
    sessionId: 'demo-session-2',
    gradient: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    emoji: '🍸',
    caption: 'Best spot in Soho tonight — come find me 🔥',
    createdAt: now - 25 * 60 * 1000,
    expiresAt: now + 5.6 * 60 * 60 * 1000,
  },
  {
    id: 'moment-2',
    userId: 'demo-user-1',
    displayName: 'Jordan',
    sessionId: 'demo-session-1',
    gradient: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
    emoji: '🎶',
    caption: 'Live music just started here — absolute vibes',
    createdAt: now - 10 * 60 * 1000,
    expiresAt: now + 5.8 * 60 * 60 * 1000,
  },
  {
    id: 'moment-3',
    userId: 'demo-user-3',
    displayName: 'Raf',
    sessionId: 'demo-session-3',
    gradient: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
    emoji: '🍝',
    caption: 'This pasta is unreal. Someone come eat with me',
    createdAt: now - 40 * 60 * 1000,
    expiresAt: now + 5.3 * 60 * 60 * 1000,
  },
  {
    id: 'moment-4',
    userId: 'demo-user-5',
    displayName: 'Priya',
    sessionId: 'demo-session-5',
    gradient: 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)',
    emoji: '🌙',
    caption: 'Perfect evening for a walk — who else is out?',
    createdAt: now - 55 * 60 * 1000,
    expiresAt: now + 5.1 * 60 * 60 * 1000,
  },
  {
    id: 'moment-5',
    userId: 'demo-user-6',
    displayName: 'Leo',
    sessionId: 'demo-session-6',
    gradient: 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
    emoji: '🎯',
    caption: "Rooftop bar just opened back up — it's packed tonight",
    createdAt: now - 5 * 60 * 1000,
    expiresAt: now + 5.9 * 60 * 60 * 1000,
  },
]

export const DEMO_LIKED_USERS = [
  { id: 'like-1', displayName: 'Ava',    age: 26, online: true,  emoji: '😊', activityType: 'drinks',  area: 'Soho',         viewCount: 7,  tagline: 'Up for anything tonight 🍸',      likedAt: now - 2 * 60 * 60 * 1000 },
  { id: 'like-2', displayName: 'Marcus', age: 30, online: true,  emoji: '😎', activityType: 'coffee',  area: 'Shoreditch',   viewCount: 12, tagline: 'Coffee first, then we\'ll see 😄', likedAt: now - 5 * 60 * 60 * 1000 },
  { id: 'like-3', displayName: 'Zoe',    age: 24, online: false, emoji: '🌸', activityType: 'food',    area: 'Camden',       viewCount: 3,  tagline: 'Foodie looking for a partner in crime', likedAt: now - 1 * 24 * 60 * 60 * 1000 },
  { id: 'like-4', displayName: 'Kai',    age: 28, online: true,  emoji: '🤙', activityType: 'hangout', area: 'Dalston',      viewCount: 9,  tagline: 'Spontaneous plans only.',          likedAt: now - 3 * 60 * 60 * 1000 },
  { id: 'like-5', displayName: 'Sofia',  age: 23, online: false, emoji: '✨', activityType: 'walk',    area: 'Notting Hill', viewCount: 5,  tagline: 'Art, walks, good vibes ✨',        likedAt: now - 2 * 24 * 60 * 60 * 1000 },
  { id: 'like-6', displayName: 'Finn',   age: 31, online: true,  emoji: '🎯', activityType: 'drinks',  area: 'Brixton',      viewCount: 14, tagline: 'Drinks after work — who\'s in?',   likedAt: now - 30 * 60 * 1000 },
]

// ─────────────────────────────────────────────────────────────────────────────
// DEMO_CATEGORY_SESSIONS
// One showcase profile per category — used to preview every card layout.
// photoURL slots: swap https://picsum.photos/seed/cat-<slug>/400/500
// with real uploads when images are provided.
// All sessions: status = 'invite_out', isSeeded = true, city = London.
// ─────────────────────────────────────────────────────────────────────────────

// Small London coordinate offsets so each pin lands in a different spot
const _LDN = (dlat, dlng) => ({
  lat: 51.5074 + dlat, lng: -0.1278 + dlng,
  fuzzedLat: 51.5074 + dlat + 0.002, fuzzedLng: -0.1278 + dlng + 0.002,
})

export const DEMO_CATEGORY_SESSIONS = [

  // ── Handmade ──────────────────────────────────────────────────────────────
  {
    id: 'cat-handmade-1', userId: 'cat-user-handmade', isSeeded: true,
    displayName: 'Zara', age: 28,
    photoURL: 'https://picsum.photos/seed/cat-handmade/400/500',
    photos: ['https://picsum.photos/seed/cat-handmade/400/500'],
    bio: 'I make jewellery, ceramics and one-of-a-kind gifts by hand. Every piece takes 2–5 days. DM to order or visit me at Spitalfields every Sunday.',
    lookingFor: 'handmade',
    activityType: 'craft', activities: ['craft', 'markets'],
    brandName: 'Zara Makes', tradeRole: 'selling', targetAudience: ['women', 'gifts'],
    priceMin: '£18', priceMax: '£120',
    tags: ['jewellery', 'ceramics', 'handmade gifts', 'custom orders'],
    instagram: 'zaramakes_ldn', tiktok: 'zaramakes',
    contactPlatform: 'instagram',
    speakingNative: 'English', speakingSecond: 'French',
    area: 'Spitalfields', city: 'London', country: 'United Kingdom',
    status: 'invite_out', userJoinedAt: new Date('2025-09-14').getTime(),
    distanceKm: 0.9, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: true, tier: 'premium',
    ..._LDN(0.01, 0.05),
  },

  // ── Craft Supplies ────────────────────────────────────────────────────────
  {
    id: 'cat-craft-supplies-1', userId: 'cat-user-craftsupplies', isSeeded: true,
    displayName: 'Priya', age: 34,
    photoURL: 'https://picsum.photos/seed/cat-craft-supplies/400/500',
    photos: ['https://picsum.photos/seed/cat-craft-supplies/400/500'],
    bio: 'Wholesale & retail craft supplies — resin, fabrics, threads, tools. I stock 400+ lines. Trade accounts welcome. Based in Walthamstow.',
    lookingFor: 'craft_supplies',
    activityType: 'craft', activities: ['craft', 'wholesale'],
    brandName: 'Priya\'s Craft Depot', tradeRole: 'selling', targetAudience: ['all'],
    priceMin: '£2', priceMax: '£85',
    tags: ['resin', 'fabric', 'thread', 'craft tools', 'wholesale'],
    instagram: 'priyas_craft_depot', website: 'https://priyascraftdepot.co.uk',
    contactPlatform: 'whatsapp',
    speakingNative: 'English', speakingSecond: 'Hindi',
    area: 'Walthamstow', city: 'London', country: 'United Kingdom',
    status: 'invite_out', userJoinedAt: new Date('2025-11-02').getTime(),
    distanceKm: 4.2, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: false, tier: 'listing',
    ..._LDN(0.04, 0.08),
  },

  // ── Art & Craft ───────────────────────────────────────────────────────────
  {
    id: 'cat-art-craft-1', userId: 'cat-user-artcraft', isSeeded: true,
    displayName: 'Marco', age: 31,
    photoURL: 'https://picsum.photos/seed/cat-art-craft/400/500',
    photos: ['https://picsum.photos/seed/cat-art-craft/400/500'],
    bio: 'Oil paintings, prints and murals. Commission work only — takes 3–6 weeks. I exhibit at Saatchi Gallery twice a year. Studio visits by appointment.',
    lookingFor: 'art_craft',
    activityType: 'art', activities: ['art', 'galleries'],
    brandName: 'Marco Studio', tradeRole: 'selling', targetAudience: ['all'],
    priceMin: '£95', priceMax: '£2,800',
    tags: ['oil painting', 'murals', 'prints', 'commission art'],
    instagram: 'marco.studio.ldn', website: 'https://marcostudio.co.uk',
    contactPlatform: 'instagram',
    speakingNative: 'Italian', speakingSecond: 'English',
    area: 'Chelsea', city: 'London', country: 'United Kingdom',
    status: 'invite_out', userJoinedAt: new Date('2025-08-21').getTime(),
    distanceKm: 2.1, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: true, tier: 'premium',
    ..._LDN(-0.02, -0.07),
  },

  // ── Buy & Sell ────────────────────────────────────────────────────────────
  {
    id: 'cat-buy-sell-1', userId: 'cat-user-buysell', isSeeded: true,
    displayName: 'Jordan', age: 26,
    photoURL: 'https://picsum.photos/seed/cat-buy-sell/400/500',
    photos: ['https://picsum.photos/seed/cat-buy-sell/400/500'],
    bio: 'I flip electronics, trainers and limited streetwear. Checked & authenticated every item. Cash or bank transfer. Shoreditch meetups only.',
    lookingFor: 'buy_sell',
    activityType: 'retail', activities: ['retail', 'markets'],
    tradeRole: 'both',
    priceMin: '£20', priceMax: '£400',
    tags: ['trainers', 'streetwear', 'electronics', 'authentic'],
    instagram: 'jordan.flips.ldn', tiktok: 'jordanflips',
    contactPlatform: 'telegram',
    speakingNative: 'English',
    area: 'Shoreditch', city: 'London', country: 'United Kingdom',
    status: 'invite_out', userJoinedAt: new Date('2026-01-10').getTime(),
    distanceKm: 1.6, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: false, tier: 'free',
    ..._LDN(0.03, 0.06),
  },

  // ── Fresh Produce ─────────────────────────────────────────────────────────
  {
    id: 'cat-fresh-produce-1', userId: 'cat-user-freshproduce', isSeeded: true,
    displayName: 'Afia', age: 38,
    photoURL: 'https://picsum.photos/seed/cat-fresh-produce/400/500',
    photos: ['https://picsum.photos/seed/cat-fresh-produce/400/500'],
    bio: 'Farm-fresh organic veg, fruit and herbs delivered to your door or collected from Brixton Market every Saturday. Supporting local growers since 2019.',
    lookingFor: 'fresh_produce',
    activityType: 'food', activities: ['food', 'markets'],
    brandName: 'Afia\'s Fresh Box', tradeRole: 'selling',
    priceMin: '£5', priceMax: '£45',
    tags: ['organic', 'veg box', 'local produce', 'farmers market'],
    instagram: 'afiafreshbox', facebook: 'AfiaFreshBox',
    contactPlatform: 'whatsapp',
    speakingNative: 'English', speakingSecond: 'Twi',
    area: 'Brixton', city: 'London', country: 'United Kingdom',
    status: 'invite_out', userJoinedAt: new Date('2025-07-30').getTime(),
    distanceKm: 3.4, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: true, tier: 'premium',
    ..._LDN(-0.04, -0.03),
  },

  // ── Fashion ───────────────────────────────────────────────────────────────
  {
    id: 'cat-fashion-1', userId: 'cat-user-fashion', isSeeded: true,
    displayName: 'Leila', age: 29,
    photoURL: 'https://picsum.photos/seed/cat-fashion/400/500',
    photos: ['https://picsum.photos/seed/cat-fashion/400/500'],
    bio: 'Independent fashion designer — ready-to-wear and made-to-measure. Stocked in 3 boutiques across London. New collection drops every season.',
    lookingFor: 'fashion',
    activityType: 'fashion', activities: ['fashion', 'markets'],
    brandName: 'Leila Atelier', tradeRole: 'selling',
    priceMin: '£65', priceMax: '£380',
    tags: ['fashion', 'made to measure', 'sustainable', 'womenswear'],
    instagram: 'leila.atelier', website: 'https://leilaatelier.com',
    contactPlatform: 'instagram',
    speakingNative: 'Arabic', speakingSecond: 'English',
    area: 'Notting Hill', city: 'London', country: 'United Kingdom',
    status: 'invite_out', userJoinedAt: new Date('2025-10-15').getTime(),
    distanceKm: 2.8, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: true, tier: 'pro',
    ..._LDN(-0.01, -0.12),
  },

  // ── Vintage ───────────────────────────────────────────────────────────────
  {
    id: 'cat-vintage-1', userId: 'cat-user-vintage', isSeeded: true,
    displayName: 'Clara', age: 33,
    photoURL: 'https://picsum.photos/seed/cat-vintage/400/500',
    photos: ['https://picsum.photos/seed/cat-vintage/400/500'],
    bio: 'Curated vintage and pre-loved clothing from the 60s–90s. I sell at Portobello Road on Saturdays and ship UK-wide. Nothing over £95.',
    lookingFor: 'vintage',
    activityType: 'fashion', activities: ['fashion', 'markets'],
    brandName: 'Clara\'s Vintage Rail', tradeRole: 'selling',
    priceMin: '£8', priceMax: '£95',
    tags: ['vintage', 'pre-loved', '90s', 'portobello', 'sustainable fashion'],
    instagram: 'clarasvintagerail', tiktok: 'clarasvintage',
    contactPlatform: 'instagram',
    speakingNative: 'English',
    area: 'Portobello', city: 'London', country: 'United Kingdom',
    status: 'invite_out', userJoinedAt: new Date('2025-12-01').getTime(),
    distanceKm: 3.1, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: false, tier: 'listing',
    ..._LDN(0.005, -0.11),
  },

  // ── Trades ────────────────────────────────────────────────────────────────
  {
    id: 'cat-trades-1', userId: 'cat-user-trades', isSeeded: true,
    displayName: 'Danny', age: 42,
    photoURL: 'https://picsum.photos/seed/cat-trades/400/500',
    photos: ['https://picsum.photos/seed/cat-trades/400/500'],
    bio: 'Qualified electrician & plumber. 18 years experience. No job too small — full rewires to fixing a leaking tap. Available weekends. Fully insured.',
    lookingFor: 'trades',
    activityType: 'services', activities: ['services'],
    brandName: 'Danny\'s Trades', tradeRole: 'selling',
    priceMin: '£65/hr', priceMax: '£POA',
    tags: ['electrician', 'plumber', 'handyman', 'fully insured', 'London'],
    facebook: 'DannyTradesLondon',
    contactPlatform: 'phone',
    speakingNative: 'English',
    area: 'Hackney', city: 'London', country: 'United Kingdom',
    status: 'invite_out', userJoinedAt: new Date('2025-06-12').getTime(),
    distanceKm: 2.6, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: true, tier: 'premium',
    ..._LDN(0.05, 0.09),
  },

  // ── Property ──────────────────────────────────────────────────────────────
  {
    id: 'cat-property-1', userId: 'cat-user-property', isSeeded: true,
    displayName: 'Natasha', age: 36,
    photoURL: 'https://picsum.photos/seed/cat-property/400/500',
    photos: ['https://picsum.photos/seed/cat-property/400/500'],
    bio: 'Property consultant with 10 years in London lettings and sales. I help landlords find tenants and buyers find their first home. Free initial consultation.',
    lookingFor: 'property',
    activityType: 'property', activities: ['property'],
    brandName: 'Natasha Property', tradeRole: 'selling',
    priceMin: 'Free consult', priceMax: '1.5% fee',
    tags: ['property', 'lettings', 'first time buyer', 'landlord advice'],
    instagram: 'natasha.property.ldn', linkedin: 'natasha-property',
    contactPlatform: 'phone',
    speakingNative: 'English', speakingSecond: 'Russian',
    area: 'Canary Wharf', city: 'London', country: 'United Kingdom',
    status: 'invite_out', userJoinedAt: new Date('2025-08-08').getTime(),
    distanceKm: 3.9, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: true, tier: 'business',
    ..._LDN(0.02, 0.14),
  },

  // ── Real Estate ───────────────────────────────────────────────────────────
  {
    id: 'cat-real-estate-1', userId: 'cat-user-realestate', isSeeded: true,
    displayName: 'Tariq', age: 44,
    photoURL: 'https://picsum.photos/seed/cat-real-estate/400/500',
    photos: ['https://picsum.photos/seed/cat-real-estate/400/500'],
    bio: 'RICS-accredited surveyor and property investment advisor. Specialising in East London buy-to-let and commercial conversions. 20+ years on the market.',
    lookingFor: 'real_estate',
    activityType: 'property', activities: ['property'],
    brandName: 'Tariq Real Estate Group', tradeRole: 'selling',
    priceMin: '£500', priceMax: '£POA',
    tags: ['buy to let', 'commercial', 'surveyor', 'property investment'],
    website: 'https://tariqrealestategroup.co.uk',
    contactPlatform: 'phone',
    speakingNative: 'English', speakingSecond: 'Urdu',
    area: 'Stratford', city: 'London', country: 'United Kingdom',
    status: 'invite_out', userJoinedAt: new Date('2025-05-20').getTime(),
    distanceKm: 5.1, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: true, tier: 'business',
    ..._LDN(0.06, 0.12),
  },

  // ── Beauty ────────────────────────────────────────────────────────────────
  {
    id: 'cat-beauty-1', userId: 'cat-user-beauty', isSeeded: true,
    displayName: 'Yemi', age: 27,
    photoURL: 'https://picsum.photos/seed/cat-beauty/400/500',
    photos: ['https://picsum.photos/seed/cat-beauty/400/500'],
    bio: 'Afro hair specialist, makeup artist and lash technician. Home visits or salon. Bridal packages available. Fully qualified, insured and DBS checked.',
    lookingFor: 'beauty',
    activityType: 'beauty', activities: ['beauty'],
    brandName: 'Yemi Beauty', tradeRole: 'selling',
    priceMin: '£35', priceMax: '£280',
    tags: ['afro hair', 'lashes', 'bridal makeup', 'mobile beauty'],
    instagram: 'yemibeautyldn', tiktok: 'yemibeauty',
    contactPlatform: 'instagram',
    speakingNative: 'English', speakingSecond: 'Yoruba',
    area: 'Peckham', city: 'London', country: 'United Kingdom',
    status: 'invite_out', userJoinedAt: new Date('2025-10-28').getTime(),
    distanceKm: 4.7, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: false, tier: 'premium',
    ..._LDN(-0.05, 0.03),
  },

  // ── Healthcare ────────────────────────────────────────────────────────────
  {
    id: 'cat-healthcare-1', userId: 'cat-user-healthcare', isSeeded: true,
    displayName: 'Dr. Aisha', age: 39,
    photoURL: 'https://picsum.photos/seed/cat-healthcare/400/500',
    photos: ['https://picsum.photos/seed/cat-healthcare/400/500'],
    bio: 'Physiotherapist specialising in sports injuries and chronic back pain. 1-to-1 sessions at my Clapham clinic or home visits within Zone 2.',
    lookingFor: 'healthcare',
    activityType: 'health', activities: ['health', 'sports'],
    brandName: 'Aisha Physio', tradeRole: 'selling',
    priceMin: '£75', priceMax: '£150',
    tags: ['physiotherapy', 'sports injury', 'back pain', 'home visits'],
    website: 'https://aishaphysio.co.uk',
    contactPlatform: 'phone',
    speakingNative: 'English', speakingSecond: 'Somali',
    area: 'Clapham', city: 'London', country: 'United Kingdom',
    status: 'invite_out', userJoinedAt: new Date('2025-09-03').getTime(),
    distanceKm: 3.6, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: true, tier: 'business',
    ..._LDN(-0.06, -0.04),
  },

  // ── Fitness & PT ──────────────────────────────────────────────────────────
  {
    id: 'cat-fitness-pt-1', userId: 'cat-user-fitnesspt', isSeeded: true,
    displayName: 'Marcus', age: 30,
    photoURL: 'https://picsum.photos/seed/cat-fitness-pt/400/500',
    photos: ['https://picsum.photos/seed/cat-fitness-pt/400/500'],
    bio: 'Personal trainer specialising in weight loss and strength. Outdoor sessions in Hyde Park or your own gym. Online plans available. First session free.',
    lookingFor: 'fitness_pt',
    activityType: 'fitness', activities: ['fitness', 'sports'],
    brandName: 'Marcus Fit', tradeRole: 'selling',
    priceMin: '£50', priceMax: '£90',
    tags: ['personal trainer', 'weight loss', 'strength', 'Hyde Park'],
    instagram: 'marcus.fit.ldn', tiktok: 'marcusfit',
    contactPlatform: 'instagram',
    speakingNative: 'English',
    area: 'Hyde Park', city: 'London', country: 'United Kingdom',
    status: 'invite_out', userJoinedAt: new Date('2025-11-15').getTime(),
    distanceKm: 1.4, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: false, tier: 'premium',
    ..._LDN(-0.005, -0.15),
  },

  // ── Wellness ──────────────────────────────────────────────────────────────
  {
    id: 'cat-wellness-1', userId: 'cat-user-wellness', isSeeded: true,
    displayName: 'Luna', age: 32,
    photoURL: 'https://picsum.photos/seed/cat-wellness/400/500',
    photos: ['https://picsum.photos/seed/cat-wellness/400/500'],
    bio: 'Yoga instructor, sound bath facilitator and mindfulness coach. Weekly classes in Shoreditch and private sessions. Retreats in Glastonbury every summer.',
    lookingFor: 'wellness',
    activityType: 'wellness', activities: ['wellness', 'yoga'],
    brandName: 'Luna Wellness', tradeRole: 'selling',
    priceMin: '£20', priceMax: '£120',
    tags: ['yoga', 'sound bath', 'mindfulness', 'meditation', 'retreats'],
    instagram: 'lunawellness.ldn', website: 'https://lunawellness.co.uk',
    contactPlatform: 'instagram',
    speakingNative: 'Spanish', speakingSecond: 'English',
    area: 'Shoreditch', city: 'London', country: 'United Kingdom',
    status: 'invite_out', userJoinedAt: new Date('2026-01-20').getTime(),
    distanceKm: 1.8, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: false, tier: 'listing',
    ..._LDN(0.03, 0.07),
  },

  // ── Catering ──────────────────────────────────────────────────────────────
  {
    id: 'cat-catering-1', userId: 'cat-user-catering', isSeeded: true,
    displayName: 'Olu', age: 41,
    photoURL: 'https://picsum.photos/seed/cat-catering/400/500',
    photos: ['https://picsum.photos/seed/cat-catering/400/500'],
    bio: 'West African catering for events — suya, jollof, puff puff, pepper soup. Weddings, corporate events and private dining. Minimum 20 guests.',
    lookingFor: 'catering',
    activityType: 'food', activities: ['food'],
    brandName: 'Olu\'s Kitchen', tradeRole: 'selling',
    priceMin: '£18pp', priceMax: '£45pp',
    tags: ['catering', 'west african', 'jollof rice', 'event catering', 'weddings'],
    instagram: 'oluskitchenldn', facebook: 'OlusKitchenLondon',
    contactPlatform: 'whatsapp',
    speakingNative: 'Yoruba', speakingSecond: 'English',
    area: 'Lewisham', city: 'London', country: 'United Kingdom',
    status: 'invite_out', userJoinedAt: new Date('2025-07-05').getTime(),
    distanceKm: 5.8, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: true, tier: 'pro',
    ..._LDN(-0.07, 0.04),
  },

  // ── Restaurant / Food & Drink ─────────────────────────────────────────────
  {
    id: 'cat-restaurant-1', userId: 'cat-user-restaurant', isSeeded: true,
    displayName: 'Nikos', age: 45,
    photoURL: 'https://picsum.photos/seed/cat-restaurant/400/500',
    photos: ['https://picsum.photos/seed/cat-restaurant/400/500'],
    bio: 'Owner of a Greek taverna in Islington — homemade moussaka, fresh octopus and proper retsina. Walk-ins welcome or book a table via Hangger.',
    lookingFor: 'restaurant',
    activityType: 'food', activities: ['food', 'drinks'],
    brandName: 'Nikos Taverna', tradeRole: 'selling', cuisineType: 'greek',
    priceMin: '£22 mains', priceMax: '£65 set menu',
    tags: ['greek food', 'taverna', 'islington', 'dine in', 'date night'],
    instagram: 'nikostaverna', website: 'https://nikostaverna.co.uk',
    contactPlatform: 'phone',
    speakingNative: 'Greek', speakingSecond: 'English',
    area: 'Islington', city: 'London', country: 'United Kingdom',
    status: 'invite_out', userJoinedAt: new Date('2025-04-18').getTime(),
    distanceKm: 2.3, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: true, tier: 'business',
    ..._LDN(0.04, -0.01),
  },

  // ── Creative ──────────────────────────────────────────────────────────────
  {
    id: 'cat-creative-1', userId: 'cat-user-creative', isSeeded: true,
    displayName: 'Ines', age: 27,
    photoURL: 'https://picsum.photos/seed/cat-creative/400/500',
    photos: ['https://picsum.photos/seed/cat-creative/400/500'],
    bio: 'Brand designer and illustrator. I build visual identities for small businesses — logo, colour, type, packaging. 5 years freelancing, 80+ clients.',
    lookingFor: 'creative',
    activityType: 'design', activities: ['design', 'branding'],
    brandName: 'Ines Creative', tradeRole: 'selling',
    priceMin: '£350', priceMax: '£2,500',
    tags: ['brand design', 'logo', 'illustration', 'packaging', 'freelance'],
    instagram: 'ines.creative', website: 'https://inescreative.com',
    contactPlatform: 'instagram',
    speakingNative: 'Portuguese', speakingSecond: 'English',
    area: 'Dalston', city: 'London', country: 'United Kingdom',
    status: 'invite_out', userJoinedAt: new Date('2025-12-10').getTime(),
    distanceKm: 2.9, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: false, tier: 'premium',
    ..._LDN(0.05, 0.07),
  },

  // ── Content Creator ───────────────────────────────────────────────────────
  {
    id: 'cat-content-creator-1', userId: 'cat-user-contentcreator', isSeeded: true,
    displayName: 'Bea', age: 24,
    photoURL: 'https://picsum.photos/seed/cat-content-creator/400/500',
    photos: ['https://picsum.photos/seed/cat-content-creator/400/500'],
    bio: 'Food & lifestyle content creator — 180k on TikTok, 42k on Instagram. I work with food brands, restaurants and lifestyle products. Brand deals from £500.',
    lookingFor: 'content_creator',
    activityType: 'content', activities: ['content', 'food'],
    brandName: 'Bea Creates', tradeRole: 'selling',
    priceMin: '£500', priceMax: '£5,000',
    tags: ['tiktok', 'instagram', 'food content', 'brand deals', 'ugc'],
    tiktok: 'beacreates', instagram: 'beacreates',
    contactPlatform: 'instagram',
    speakingNative: 'English',
    area: 'Hackney', city: 'London', country: 'United Kingdom',
    status: 'invite_out', userJoinedAt: new Date('2026-02-14').getTime(),
    distanceKm: 2.1, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: true, tier: 'pro',
    ..._LDN(0.04, 0.10),
  },

  // ── Photography ───────────────────────────────────────────────────────────
  {
    id: 'cat-photography-1', userId: 'cat-user-photography', isSeeded: true,
    displayName: 'Kai', age: 29,
    photoURL: 'https://picsum.photos/seed/cat-photography/400/500',
    photos: ['https://picsum.photos/seed/cat-photography/400/500'],
    bio: 'Freelance photographer for portraits, events and brand shoots. Based in East London. Fully edited digital delivery within 48 hours. Reel add-on available.',
    lookingFor: 'photography',
    activityType: 'photography', activities: ['photography'],
    brandName: 'Kai Shoots', tradeRole: 'selling',
    priceMin: '£150', priceMax: '£950',
    tags: ['photography', 'portraits', 'events', 'brand shoot', 'east london'],
    instagram: 'kai.shoots.ldn', website: 'https://kaishoots.com',
    contactPlatform: 'instagram',
    speakingNative: 'English', speakingSecond: 'Japanese',
    area: 'Bethnal Green', city: 'London', country: 'United Kingdom',
    status: 'invite_out', userJoinedAt: new Date('2025-09-22').getTime(),
    distanceKm: 1.7, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: false, tier: 'premium',
    ..._LDN(0.02, 0.08),
  },

  // ── Music ─────────────────────────────────────────────────────────────────
  {
    id: 'cat-music-1', userId: 'cat-user-music', isSeeded: true,
    displayName: 'Dani', age: 26,
    photoURL: 'https://picsum.photos/seed/cat-music/400/500',
    photos: ['https://picsum.photos/seed/cat-music/400/500'],
    bio: 'Session musician and music producer. Piano, keys and synth. I produce R&B, lo-fi and soul. Open to collaborations, live sessions and recording credits.',
    lookingFor: 'music',
    activityType: 'music', activities: ['music'],
    brandName: 'Dani Sounds', tradeRole: 'selling',
    priceMin: '£80', priceMax: '£500',
    tags: ['music producer', 'session musician', 'r&b', 'lo-fi', 'piano'],
    instagram: 'dani.sounds', tiktok: 'danisounds',
    contactPlatform: 'instagram',
    speakingNative: 'English', speakingSecond: 'Spanish',
    area: 'Brixton', city: 'London', country: 'United Kingdom',
    status: 'invite_out', userJoinedAt: new Date('2026-01-03').getTime(),
    distanceKm: 3.2, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: false, tier: 'listing',
    ..._LDN(-0.04, -0.02),
  },

  // ── Professional Services ─────────────────────────────────────────────────
  {
    id: 'cat-professional-1', userId: 'cat-user-professional', isSeeded: true,
    displayName: 'Rachel', age: 40,
    photoURL: 'https://picsum.photos/seed/cat-professional/400/500',
    photos: ['https://picsum.photos/seed/cat-professional/400/500'],
    bio: 'Chartered accountant and tax advisor for freelancers and small businesses. Annual accounts, VAT returns and HMRC investigations. Free 30-min call.',
    lookingFor: 'professional',
    activityType: 'business', activities: ['business'],
    brandName: 'Rachel & Co Accountants', tradeRole: 'selling',
    priceMin: '£120', priceMax: '£850/yr',
    tags: ['accountant', 'tax', 'VAT', 'freelancer accounts', 'HMRC'],
    website: 'https://rachelandco.co.uk', linkedin: 'rachel-and-co',
    contactPlatform: 'phone',
    speakingNative: 'English',
    area: 'City of London', city: 'London', country: 'United Kingdom',
    status: 'invite_out', userJoinedAt: new Date('2025-06-01').getTime(),
    distanceKm: 0.8, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: true, tier: 'business',
    ..._LDN(0.01, 0.02),
  },

  // ── Legal ─────────────────────────────────────────────────────────────────
  {
    id: 'cat-legal-1', userId: 'cat-user-legal', isSeeded: true,
    displayName: 'James', age: 37,
    photoURL: 'https://picsum.photos/seed/cat-legal/400/500',
    photos: ['https://picsum.photos/seed/cat-legal/400/500'],
    bio: 'Solicitor specialising in employment law and tenancy disputes. Fixed fees, no hidden costs. Over 200 cases settled. Free initial 20-min consultation.',
    lookingFor: 'legal',
    activityType: 'legal', activities: ['legal'],
    brandName: 'James Clarke Solicitors', tradeRole: 'selling',
    priceMin: '£180', priceMax: '£POA',
    tags: ['solicitor', 'employment law', 'tenancy dispute', 'fixed fee'],
    website: 'https://jamesclarke.law', linkedin: 'james-clarke-solicitor',
    contactPlatform: 'phone',
    speakingNative: 'English',
    area: 'Holborn', city: 'London', country: 'United Kingdom',
    status: 'invite_out', userJoinedAt: new Date('2025-05-14').getTime(),
    distanceKm: 0.6, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: true, tier: 'business',
    ..._LDN(0.01, -0.02),
  },

  // ── Technology ────────────────────────────────────────────────────────────
  {
    id: 'cat-technology-1', userId: 'cat-user-technology', isSeeded: true,
    displayName: 'Arjun', age: 29,
    photoURL: 'https://picsum.photos/seed/cat-technology/400/500',
    photos: ['https://picsum.photos/seed/cat-technology/400/500'],
    bio: 'Full-stack developer building web and mobile apps for startups. React, Node, Supabase. MVP in 6 weeks guaranteed. Happy to NDA. Portfolio on request.',
    lookingFor: 'technology',
    activityType: 'tech', activities: ['tech'],
    brandName: 'Arjun Dev', tradeRole: 'selling',
    priceMin: '£450/day', priceMax: '£POA',
    tags: ['web dev', 'mobile app', 'react', 'startup', 'MVP'],
    instagram: 'arjun.dev', website: 'https://arjundev.io',
    contactPlatform: 'telegram',
    speakingNative: 'English', speakingSecond: 'Hindi',
    area: 'Shoreditch', city: 'London', country: 'United Kingdom',
    status: 'invite_out', userJoinedAt: new Date('2026-02-01').getTime(),
    distanceKm: 1.3, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: false, tier: 'premium',
    ..._LDN(0.03, 0.05),
  },

  // ── Education ─────────────────────────────────────────────────────────────
  {
    id: 'cat-education-1', userId: 'cat-user-education', isSeeded: true,
    displayName: 'Amara', age: 35,
    photoURL: 'https://picsum.photos/seed/cat-education/400/500',
    photos: ['https://picsum.photos/seed/cat-education/400/500'],
    bio: 'Secondary school teacher and private tutor. Maths, Physics and Chemistry. GCSE and A-Level specialist. Small groups (max 4) or 1-to-1. CRB checked.',
    lookingFor: 'education',
    activityType: 'education', activities: ['education'],
    brandName: 'Amara Tutors', tradeRole: 'selling',
    priceMin: '£40/hr', priceMax: '£65/hr',
    tags: ['tutor', 'maths', 'physics', 'GCSE', 'A-level'],
    facebook: 'AmaraTutorsLondon',
    contactPlatform: 'whatsapp',
    speakingNative: 'French', speakingSecond: 'English',
    area: 'Streatham', city: 'London', country: 'United Kingdom',
    status: 'invite_out', userJoinedAt: new Date('2025-09-01').getTime(),
    distanceKm: 5.4, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: false, tier: 'listing',
    ..._LDN(-0.08, -0.01),
  },

  // ── Coaching ──────────────────────────────────────────────────────────────
  {
    id: 'cat-coaching-1', userId: 'cat-user-coaching', isSeeded: true,
    displayName: 'Simone', age: 41,
    photoURL: 'https://picsum.photos/seed/cat-coaching/400/500',
    photos: ['https://picsum.photos/seed/cat-coaching/400/500'],
    bio: 'ICF-accredited life and career coach. I help people change careers, overcome burnout and build confidence. 12-week programmes or single sessions.',
    lookingFor: 'coaching',
    activityType: 'coaching', activities: ['coaching'],
    brandName: 'Simone Coaching', tradeRole: 'selling',
    priceMin: '£90', priceMax: '£1,200/programme',
    tags: ['life coach', 'career change', 'burnout', 'confidence', 'ICF'],
    instagram: 'simone.coaching', website: 'https://simonecoaching.co.uk',
    contactPlatform: 'instagram',
    speakingNative: 'English', speakingSecond: 'French',
    area: 'Richmond', city: 'London', country: 'United Kingdom',
    status: 'invite_out', userJoinedAt: new Date('2025-10-11').getTime(),
    distanceKm: 8.2, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: true, tier: 'pro',
    ..._LDN(-0.05, -0.20),
  },

  // ── Hiring ────────────────────────────────────────────────────────────────
  {
    id: 'cat-hiring-1', userId: 'cat-user-hiring', isSeeded: true,
    displayName: 'Tom', age: 33,
    photoURL: 'https://picsum.photos/seed/cat-hiring/400/500',
    photos: ['https://picsum.photos/seed/cat-hiring/400/500'],
    bio: 'Tech recruiter placing engineers, designers and PMs at London startups. No fee to candidates. I currently have 14 open roles across Series A–C companies.',
    lookingFor: 'hiring',
    activityType: 'business', activities: ['business'],
    brandName: 'Tom Recruit', tradeRole: 'both',
    priceMin: 'No fee', priceMax: 'Employer-paid',
    tags: ['tech jobs', 'startup jobs', 'engineering roles', 'product roles'],
    linkedin: 'tom-recruit-ldn', instagram: 'tomrecruitldn',
    contactPlatform: 'phone',
    speakingNative: 'English',
    area: 'Old Street', city: 'London', country: 'United Kingdom',
    status: 'invite_out', userJoinedAt: new Date('2026-03-01').getTime(),
    distanceKm: 1.1, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: false, tier: 'listing',
    ..._LDN(0.04, 0.04),
  },

  // ── Freelance ─────────────────────────────────────────────────────────────
  {
    id: 'cat-freelance-1', userId: 'cat-user-freelance', isSeeded: true,
    displayName: 'Sasha', age: 28,
    photoURL: 'https://picsum.photos/seed/cat-freelance/400/500',
    photos: ['https://picsum.photos/seed/cat-freelance/400/500'],
    bio: 'Freelance copywriter and content strategist. I write for fintech, health and lifestyle brands. Fast turnaround, SEO-optimised. Published in Forbes and Wired.',
    lookingFor: 'freelance',
    activityType: 'writing', activities: ['writing', 'content'],
    brandName: 'Sasha Writes', tradeRole: 'selling',
    priceMin: '£150', priceMax: '£1,800/project',
    tags: ['copywriting', 'content strategy', 'SEO', 'fintech', 'lifestyle'],
    website: 'https://sashawrites.com', linkedin: 'sasha-writes',
    contactPlatform: 'phone',
    speakingNative: 'English',
    area: 'Farringdon', city: 'London', country: 'United Kingdom',
    status: 'invite_out', userJoinedAt: new Date('2025-11-25').getTime(),
    distanceKm: 0.7, expiresAtMs: now + 6 * 60 * 60 * 1000,
    isVerified: false, tier: 'listing',
    ..._LDN(0.01, -0.03),
  },

  // ── Social / Meet New People ───────────────────────────────────────────────
  {
    id: 'cat-meet-new-1', userId: 'cat-user-meetnew', isSeeded: true,
    displayName: 'Felix', age: 27,
    photoURL: 'https://picsum.photos/seed/cat-meet-new/400/500',
    photos: ['https://picsum.photos/seed/cat-meet-new/400/500'],
    bio: 'New to London from Berlin. Looking to meet genuine people — not just another WhatsApp group that never plans anything. Coffee or evening drinks?',
    lookingFor: 'meet_new',
    activityType: 'hangout', activities: ['hangout', 'coffee', 'drinks'],
    speakingNative: 'German', speakingSecond: 'English',
    area: 'Angel', city: 'London', country: 'United Kingdom',
    status: 'invite_out', userJoinedAt: new Date('2026-03-20').getTime(),
    distanceKm: 1.9, expiresAtMs: now + 6 * 60 * 60 * 1000,
    ..._LDN(0.03, -0.005),
  },

  // ── Friendship ────────────────────────────────────────────────────────────
  {
    id: 'cat-friendship-1', userId: 'cat-user-friendship', isSeeded: true,
    displayName: 'Kezia', age: 30,
    photoURL: 'https://picsum.photos/seed/cat-friendship/400/500',
    photos: ['https://picsum.photos/seed/cat-friendship/400/500'],
    bio: 'Just moved back to London after 3 years in Sydney. Looking for proper friends, not followers. Love hiking, board games and independent cinema.',
    lookingFor: 'friendship',
    activityType: 'hangout', activities: ['hangout', 'walk', 'cinema'],
    speakingNative: 'English',
    area: 'Stoke Newington', city: 'London', country: 'United Kingdom',
    status: 'invite_out', userJoinedAt: new Date('2026-03-15').getTime(),
    distanceKm: 3.5, expiresAtMs: now + 6 * 60 * 60 * 1000,
    ..._LDN(0.06, 0.02),
  },

  // ── Sports / Active ───────────────────────────────────────────────────────
  {
    id: 'cat-sports-1', userId: 'cat-user-sports', isSeeded: true,
    displayName: 'Ravi', age: 25,
    photoURL: 'https://picsum.photos/seed/cat-sports/400/500',
    photos: ['https://picsum.photos/seed/cat-sports/400/500'],
    bio: 'Looking for 5-a-side teammates and running partners. I run 5k every morning in Victoria Park. Also up for tennis, padel and swimming. Competitive but friendly.',
    lookingFor: 'sports',
    activityType: 'sports', activities: ['sports', 'run', 'tennis'],
    speakingNative: 'English', speakingSecond: 'Tamil',
    area: 'Victoria Park', city: 'London', country: 'United Kingdom',
    status: 'invite_out', userJoinedAt: new Date('2026-02-28').getTime(),
    distanceKm: 2.7, expiresAtMs: now + 6 * 60 * 60 * 1000,
    ..._LDN(0.05, 0.11),
  },

  // ── Gaming ────────────────────────────────────────────────────────────────
  {
    id: 'cat-gaming-1', userId: 'cat-user-gaming', isSeeded: true,
    displayName: 'Ellie', age: 23,
    photoURL: 'https://picsum.photos/seed/cat-gaming/400/500',
    photos: ['https://picsum.photos/seed/cat-gaming/400/500'],
    bio: 'Gamer girl — PC, PS5 and board games. Looking for chill people to game with IRL or online. I co-run a board game night every other Thursday in Soho.',
    lookingFor: 'gaming',
    activityType: 'gaming', activities: ['gaming', 'hangout'],
    speakingNative: 'English',
    area: 'Soho', city: 'London', country: 'United Kingdom',
    status: 'invite_out', userJoinedAt: new Date('2026-03-10').getTime(),
    distanceKm: 0.5, expiresAtMs: now + 6 * 60 * 60 * 1000,
    ..._LDN(0.01, -0.01),
  },

]
